- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Remove default html
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent

- name: Downlaod and unarchive file
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy expense nginx config file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Enable nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true


