format_version: 10
pipelines:
  frontend:
    group: defaultGroup
    materials:
      git-2058dd3:
        git: https://github.com/iteration-1/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash
                    run_if: passed
